<?php
require __DIR__.'/../inc/bootstrap.php';
admin_required();
ensure_visits_table();
$total=(int)db()->query('SELECT COUNT(*) FROM visits')->fetchColumn();
$today=(int)db()->query('SELECT COUNT(*) FROM visits WHERE visited_at >= CURDATE()')->fetchColumn();
$unique=(int)db()->query('SELECT COUNT(DISTINCT ip_address) FROM visits')->fetchColumn();
$countries=db()->query('SELECT country,COUNT(*) AS visits,COUNT(DISTINCT ip_address) AS visitors FROM visits GROUP BY country ORDER BY visits DESC LIMIT 50')->fetchAll();
$visits=db()->query('SELECT ip_address,country,page,visited_at FROM visits ORDER BY visited_at DESC LIMIT 250')->fetchAll();
?><!doctype html><html lang="tr"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Raporlar - Kirpisoft CMS</title><link rel="stylesheet" href="admin.css"><body><header><b>Kirpisoft CMS</b><nav><a href="index.php">Site ayarları</a><a href="../index.php" target="_blank">Siteyi aç</a><a href="logout.php">Çıkış</a></nav></header><main class="panel reports"><h1>Raporlar</h1><section class="stats"><div class="card stat"><span>Toplam görüntülenme</span><strong><?=number_format($total,0,',','.')?></strong></div><div class="card stat"><span>Bugünkü görüntülenme</span><strong><?=number_format($today,0,',','.')?></strong></div><div class="card stat"><span>Tekil IP</span><strong><?=number_format($unique,0,',','.')?></strong></div></section><section class="card"><h2>Ülke bazında ziyaretçiler</h2><div class="table-wrap"><table><thead><tr><th>Ülke</th><th>Görüntülenme</th><th>Tekil IP</th></tr></thead><tbody><?php if(!$countries):?><tr><td colspan="3">Henüz ziyaret kaydı yok.</td></tr><?php endif?><?php foreach($countries as $row):?><tr><td><?=e($row['country'])?></td><td><?=number_format((int)$row['visits'],0,',','.')?></td><td><?=number_format((int)$row['visitors'],0,',','.')?></td></tr><?php endforeach?></tbody></table></div></section><section class="card"><h2>Son ziyaretler</h2><div class="table-wrap"><table><thead><tr><th>Tarih</th><th>IP adresi</th><th>Ülke</th><th>Sayfa</th></tr></thead><tbody><?php if(!$visits):?><tr><td colspan="4">Henüz ziyaret kaydı yok.</td></tr><?php endif?><?php foreach($visits as $row):?><tr><td><?=e($row['visited_at'])?></td><td><?=e($row['ip_address'])?></td><td><?=e($row['country'])?></td><td><?=e($row['page'])?></td></tr><?php endforeach?></tbody></table></div></section></main></body></html>
